language:
  ruby

rvm:
  - '2.1'
  - '2.2'
  - '2.3.0'
  - '2.4.0'

script:
  - bundle exec rubocop
  - bundle exec rspec
  - rake install
  - lc
  - lc -d
  - lc -f
  - lc -sd
  - lc -sf
  - lc -1
  - lc -r

install:
  - gem install bundler
  - bundle install